---
- name: Create users on all servers
  hosts: dbserver
  tasks:
    - name: Create users
      user:
        name: Ramesh
        password: intelliqit
        home: /tmp/Ramesh
        uid: 9090
        shell: /bin/bash
        comment: "A normal user"

...
