---
- name: Copy customsied tomcat-uers.xml file
  copy:
    src: "{{file1}}"
    dest: "{{dest1}}"
- name: Change port of tocmat from 8080 to 9090
  replace: 
    regexp: "{{port1}}"
    replace: "{{port2}}"
    path: "{{path1}}"
  notify: Check url response
...
